# /* < DTS2011090704268 jiaxianghong 20110914 begin */
rsm-objs   :=  rsm_main.o rsm_find_func_addr.o hung_task.o

obj-$(CONFIG_HUAWEI_HUNGTASK)  +=  rsm.o
# /* DTS2011090704268 jiaxianghong 20110914 end > */
